### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by ghosthamlet** [dojoteef/storium-gpt2#1]
Hi, your paper "STORIUM: A Dataset and Evaluation Platform for Machine-in-the-Loop Story Generation" is wonderful, 
I am very interested in the STORIUM dataset, and registered on storium.cs.umass.edu, but still can't download, when clicking the download button in the popup, it just redirects back to the home page.

**Comment by zipJiang** [comment]
Same problem here. Found the task really interesting but still can't download the dataset after registration.

**Comment by dojoteef** [comment]
Sorry for the late response! The developers of Storium (who I partnered with for the research) only want to provide access to users with a legitimate research interest. So I now I have to manually approve individuals after they register. I will follow up with you both in email.
